/*
@Author: Franco Ribeiro Borba
@Description: Wallet ledger repository. It only inserts, because the table
refuses UPDATE, DELETE and TRUNCATE at the database level: a financial
correction is a new entry and never an edit, which is what keeps the history
auditable and lets a reconciliation rebuild any balance from credits minus
debits. The uniqueness of (walletId, transactionId) is the last line of defence
against a duplicated movement, so a second attempt to post the same operation
comes back as ErrConcurrentUpdate instead of a second debit.
@Date : 20/09/2026
@Update: -
*/
package postgres

import (
	"context"
	"fmt"

	"github.com/FrancoBorba/distributed-wallet-api/cmd/internal/domain"
	"github.com/FrancoBorba/distributed-wallet-api/cmd/internal/usecase"
)

// LedgerRepository appends entries to the wallet history.
type LedgerRepository struct {
	querier Querier
}

// NewLedgerRepository binds the repository to a querier.
func NewLedgerRepository(querier Querier) *LedgerRepository {
	return &LedgerRepository{querier: querier}
}

// Insert appends one movement. The seq column is generated by the database and
// is not part of the entry, since no domain invariant depends on it: it exists
// to give the cursor pagination of the ledger a stable ordering.
func (r *LedgerRepository) Insert(ctx context.Context, entry *domain.WalletLedgerEntry) error {
	_, err := r.querier.Exec(ctx,
		`INSERT INTO wallet_ledger (
			id, wallet_id, transaction_id, direction, currency,
			amount_cents, balance_before_cents, balance_after_cents, created_at
		) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,
		entry.ID(), entry.WalletID(), entry.TransactionID(),
		string(entry.Direction()), entry.Currency(),
		entry.Amount().Cents(), entry.BalanceBefore().Cents(), entry.BalanceAfter().Cents(),
		entry.CreatedAt(),
	)
	if isUniqueViolation(err, "wallet_ledger_wallet_transaction_key") {
		// This operation already moved this wallet. Whatever led us here, the
		// movement is not applied twice.
		return fmt.Errorf("%w: transaction %s already posted", usecase.ErrConcurrentUpdate, entry.TransactionID())
	}
	if err != nil {
		return fmt.Errorf("insert ledger entry %s: %w", entry.ID(), err)
	}

	return nil
}
